INSERT OR REPLACE INTO exercises (id, name, category, default_sets, default_reps, default_weight, note, image_url, sort_order, is_timed) VALUES
('warmup_bike','Hometrainer','warmup',1,'5 min','Licht','Lage weerstand, opwarmen','/images/warmup_bike.svg',1,1),
('warmup_quad_sets','Quad Sets (isometrisch)','warmup',3,'10','Lichaamsgewicht','5 seconden vasthouden per rep','/images/warmup_quad_sets.svg',2,0),
('warmup_slr','Straight Leg Raises','warmup',2,'15 per been','Lichaamsgewicht','Alle richtingen: voor, zij, achter','/images/warmup_slr.svg',3,0),
('a_leg_press','Leg Press','blok_a',3,'20','35 kg × 2','⚠️ Max 70-80° knieflexie (meniscus!)','/images/a_leg_press.svg',10,0),
('a_leg_curl','Leg Curl (machine)','blok_a',3,'15','35 kg','Langzaam, geen momentum','/images/a_leg_curl.svg',11,0),
('a_glute_bridge','Glute Bridges','blok_a',3,'15','Lichaamsgewicht','2 sec squeeze bovenaan','/images/a_glute_bridge.svg',12,0),
('a_calf_raise','Calf Raises (staand)','blok_a',3,'20','Lichaamsgewicht','Bilateraal, volle ROM','/images/a_calf_raise.svg',13,0),
('b_lat_pull','Lat Pulldown','blok_b',3,'12','27 kg','Schouderbladen samentrekken','/images/b_lat_pull.svg',20,0),
('b_chest_press','Chest Press','blok_b',3,'12','17,5 kg × 2 + stang','Gecontroleerd tempo','/images/b_chest_press.svg',21,0),
('b_ohp','Overhead Press','blok_b',3,'12','10 kg × 2 + stang','Core aanspannen','/images/b_ohp.svg',22,0),
('b_trap_bar_dl','Trap Bar Deadlift','blok_b',3,'12','5 kg × 2 + bar','Rug recht, vanuit de heupen','/images/b_trap_bar_dl.svg',23,0),
('c_band_walks','Lateral Band Walks','blok_c',2,'15 per richting','Weerstandsband','Knieën naar buiten duwen','/images/c_band_walks.svg',30,0),
('c_clamshells','Clamshells (met band)','blok_c',2,'15 per kant','Weerstandsband','Heup stabiel houden','/images/c_clamshells.svg',31,0),
('c_plank','Plank (front)','blok_c',3,'30-45 sec','Lichaamsgewicht','Heupen niet laten zakken','/images/c_plank.svg',32,1),
('c_dead_bugs','Dead Bugs','blok_c',2,'10 per kant','Lichaamsgewicht','Onderrug op de grond houden','/images/c_dead_bugs.svg',33,0),
('c_balance','Eenbenig Staan','blok_c',3,'30 sec per been','Lichaamsgewicht','Eventueel op balanspad/bosu','/images/c_balance.svg',34,1),
('cooldown_bike','Hometrainer (uitfietsen)','cooldown',1,'5 min','Licht','Rustig uitfietsen','/images/cooldown_bike.svg',40,1),
('cooldown_ice','IJzen knie','cooldown',1,'15-20 min','—','Direct na sessie','/images/cooldown_ice.svg',41,1);
